### ISSUE TITLE
Setup other testnets

### ISSUE THREAD

**Issue by palango** [raiden-network/explorer#113]
We need to setup the explorer for our other testnets

- [x] Setup backends (Done in aa140d112a13779dd4a14aa161875ea1b80d223f)
- [x] Setup frontends

**Comment by palango** [comment]
@kelsos Can we add an option in the config file to set the testnet name?

**Comment by kelsos** [comment]
Yes of course. Can you open an issue? I will have it done by tonight after I leave the conference.

**Comment by palango** [comment]
Finished as of e62d06de0e6731b2f9cdbf504cfcdd241640205e
