### ISSUE TITLE
Add option to show testnet token networks as well

### ISSUE THREAD

**Issue by palango** [raiden-network/explorer#118]
For testing it would be nice to be able to check the topology.

For this we should add an option to show the Test Tokens as well. @kelsos Any ideas on how to do this best?

**Comment by kelsos** [comment]
Do we want it to be user configurable?

**Comment by palango** [comment]
I'm not sure, one could argue for defining this at compile time or runtime. What do you think? 

Maybe its best to not do the filtering at all? As they won't be on mainnet anyways and for testnets people might be interested.

**Comment by kelsos** [comment]
Remove completely sounds fine too. Since there is lazy loading and searching now it would make more sense.

**Comment by palango** [comment]
> Since there is lazy loading and searching now it would make more sense.

Sounds good to me!
