### ISSUE TITLE
Visualization not properly updated on channel delete

### ISSUE THREAD

**Issue by palango** [raiden-network/explorer#122]
I'm not 100% sure, but I think I saw the visualization not update properly when a channel was closed.

The number of channels was properly decremented, but the channel still displayed in the visualization as open.
After a refresh it's properly gone.

**Comment by palango** [comment]
Jacob also remembers that the total channel count updated properly, but think the numbers in the `Channel Overview` didn't update automatically.

**Comment by kelsos** [comment]
Ok give me some time to investigate and see what might be wrong.
