### ISSUE TITLE
Search dropdown strangely hovers while scrolling

### ISSUE THREAD

**Issue by BOR4** [raiden-network/explorer#140]
I noticed that while I scroll while I have a search dropdown selected it hovers around strangely. I made a video because it explains it best.
[raiden_explorer.mp4.zip](https://github.com/raiden-network/explorer/files/2670830/raiden_explorer.mp4.zip)

**Comment by manuelwedler** [comment]
Seems more stable to me now. That the dropdown moves above the field if there is not enough space below is intended by Angular Material.
