### ISSUE TITLE
Nonexistent routes return error

### ISSUE THREAD

**Issue by BOR4** [raiden-network/explorer#141]
For example: https://explorer.raiden.network/home returns: Cannot GET /home (picture)
![image](https://user-images.githubusercontent.com/40821065/49853313-09e3d900-fde7-11e8-8276-416d6a6fff2f.png)

I think it would be nicer if either "page not found" is returned or default route which exists.

**Comment by palango** [comment]
Yes, that route was removed. I fixed the link in the Readme.
