### ISSUE TITLE
explorer.raiden.network is down

### ISSUE THREAD

**Issue by Kisgus** [raiden-network/explorer#157]
## Description

When going to https://explorer.raiden.network/tokens the site keeps loading as below

![Screen Shot 2019-04-17 at 9 27 15 AM](https://user-images.githubusercontent.com/18598519/56269134-499f3200-60f3-11e9-9a7c-d85f0f6ddad7.png)

When reloading the page the following error message appear

![Screen Shot 2019-04-17 at 9 27 21 AM](https://user-images.githubusercontent.com/18598519/56269147-56238a80-60f3-11e9-9941-0930a022c7cb.png)

## Solution

Show me the tokens :)

**Comment by palango** [comment]
Seems like there were connection issues to the hosted nodes, and the mainnet explorer backend didn’t restart properly. Fixed by a restart.

**Comment by mat7ias** [comment]
@palango the explorer is down

**Comment by palango** [comment]
Thanks for the notification @mat7ias . I'll have a look and we have to start on some monitoring solution.
