### ISSUE TITLE
Fix Görli explorer to include WizardToken [WIZ] 

### ISSUE THREAD

**Issue by franzihei** [raiden-network/explorer#167]
For the launch of the Raiden Wizard it would be great if the Görli testnet Raiden explorer could show the WizardToken [WIZ] token network.

![image](https://user-images.githubusercontent.com/41991517/61957862-7c917580-afc0-11e9-9456-27e33e73970a.png)

**Comment by mat7ias** [comment]
Not sure if this is the same issue although it might be, depending on what version you're on: I registered a token network using v0.100.4 and opened some channels which never showed on the explorer even after checking back a few days later. I tried opening channels on nodes running v0.100.3 and it showed up on the explorer almost instantly after opening+funding.

**Comment by palango** [comment]
This is the same issue. The backend hasn't been updated for a while, so it looks for token in older contracts.

We need to decide if we want to update the old backend or write a new endpoint for the PFS services.

**Comment by palango** [comment]
Fixed by https://github.com/raiden-network/explorer/pull/168
