### ISSUE TITLE
[SP 5] Make the Explorer Alderaan Release Ready

### ISSUE THREAD

**Issue by Dominik1999** [raiden-network/explorer#200]
Before we announce the Alderaan Release to the public, we need to upgrade the Raiden Explorer

- [x] Raiden Explorer needs an upgrade to the new contracts 
- [x] Raiden Explorer needs an upgrade of the web3 package

**Comment by christianbrb** [comment]
@Dominik1999 Is this the reason why the spinner is turning and no data is loading at the moment

eg. https://goerli.explorer.raiden.network/tokens

**Comment by Dominik1999** [comment]
yes

**Comment by palango** [comment]
The mainnet backend still complains about some events that aren't synced, but this will be fixed once we switch to the offical mainnet contracts release.
