### ISSUE TITLE
Update angular and dependencies

### ISSUE THREAD

**Issue by kelsos** [raiden-network/explorer#215]
The dependencies of the explorer page have not been updated for a long period.
As a result, we are still using Angular 7, while angular 9.0 is the latest.

After the Alderaan changes are done to the explorer page we should go ahead and update the dependencies. It would also be a nice idea to include some update mechanism to regularly keep dependencies up to date at least the minor/patch version.

We tried depandabot, but as an alternative, we should also check [renovate](https://github.com/renovatebot/renovate), since it supports making grouped PRs.

@Dominik1999 @manuelwedler I am supposing that explorer changes are done in regards to Alderaan, can you confirm?

**Comment by manuelwedler** [comment]
I already updated the mainnet frontend to the new overview. Other than that there is nothing that I know of.

**Comment by manuelwedler** [comment]
Done in #230 & #219
