### ISSUE TITLE
Fix Mobile view 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/explorer#216]
The mobile view of the explorer could be improved (see screenshot)

![4F4BA461-F8FE-45EB-879E-DAD9EF8A9B9B](https://user-images.githubusercontent.com/35398162/83606324-b08edd00-a579-11ea-9982-0fcfb5def49e.jpeg)

@manuelwedler

**Comment by manuelwedler** [comment]
@christianbrb Thanks for the issue. In which browser is this? I can't reproduce it in Chrome on Android.

**Comment by christianbrb** [comment]
It‘s in Safari
