### ISSUE TITLE
Token network carousel animation bug

### ISSUE THREAD

**Issue by manuelwedler** [raiden-network/explorer#226]
The animation of the token network carousel stopped working properly. I don't know which change could have introduced this bug.
The animation should actually make a smooth transition between the token networks. 
![explorer-animation-bug2020-07-28 10-12](https://user-images.githubusercontent.com/34456797/88638099-4f880f00-d0bb-11ea-9b79-21753abdf1c4.gif)

**Comment by christianbrb** [comment]
Is this still a bug?

**Comment by manuelwedler** [comment]
Yes, it is. I will have a look.
