### ISSUE TITLE
Use HTTPS

### ISSUE THREAD

**Issue by palango** [raiden-network/explorer#41]
We should get a certificate from LetsEncrypt and only use HTTPS

**Comment by ulope** [comment]
That can be automated very easily by using Traefik.

See the [config](https://github.com/raiden-network/raiden-transport/blob/7cbe399d959ca6a1c1814afcbd14943064f3785b/docker-compose.yml#L169-L190) in [raiden-transport](https://github.com/raiden-network/raiden-transport/blob/7cbe399d959ca6a1c1814afcbd14943064f3785b/config/traefik/traefik.toml)
