### ISSUE TITLE
Weird hover issue on main buttons

### ISSUE THREAD

**Issue by ulope** [raiden-network/explorer#52]
In Safari hovering over the main buttons causes some weird flickering: ![](https://ds.ulo.pe/xCB7Csl5xq.gif)

Maybe related to the tooltip.

**Comment by palango** [comment]
@ulope Which version of Safari did you use?

**Comment by ulope** [comment]
Yeah still happens, although looks slightly different: ![](https://ds.ulo.pe/sMHymKQoS0.gif)

It seems that while the tooltip is animating the brightness changes back to pre-hover value.

I'm using Safari 12.0

**Comment by palango** [comment]
So weird, I don't see this on Safari 12.0

**Comment by palango** [comment]
@kelsos Any idea on this one?

**Comment by palango** [comment]
Doesn't happen for me on Safari 12 either. So Ulo, it's you strange computers fault ;)
