### ISSUE TITLE
Network graph improvements

### ISSUE THREAD

**Issue by kelsos** [raiden-network/explorer#59]
I am opening this to keep some notes on ideas for future improvement of the network graph functionality.

* Grouping of nodes belonging to the same token network: [Grouping nodes in a Force-Directed Graph](https://bl.ocks.org/XavierGimenez/a8e8c5e9aed71ba96bd52332682c0399)
* Highlight neighbor connections when user presses a node: [Interactive & Dynamic Force-Directed Graphs with D3](https://medium.com/ninjaconcept/interactive-dynamic-force-directed-graphs-with-d3-da720c6d7811)

**Comment by ulope** [comment]
Just an observation: the graph is a bit hard to discover on typical screen sizes. The upper part of the page looks pretty 'complete', not triggering people to scroll, if that makes sense.

**Comment by kelsos** [comment]
Grouping was not working really well when tried.
