### ISSUE TITLE
Visualization improvements

### ISSUE THREAD

**Issue by palango** [raiden-network/explorer#60]
Some ideas for further improving the visualization:
- [ ] Don't let the nodes run out of the visualization area
- [x] Add better tooltips (show them faster, show more infos)
- [x] Make nodes selectable and when selected highlight channels

**Comment by kelsos** [comment]
It seems that bounding the nodes in the visible area can make the graph really hard to view so we will not implement it at the moment. 
However we may investigate on how to make the svg zoomable/draggable as a whole so that the user can see the nodes.
