### ISSUE TITLE
Show node status

### ISSUE THREAD

**Issue by palango** [raiden-network/explorer#74]
It would be nice to display information about online Raiden nodes as well.

However this creates some problems:
- How to know which nodes are online (maybe from matrix presence)
- What additional info should be displayed about them?

**Comment by christianbrb** [comment]
This could now get implemented using the status information from Matrix

**Comment by christianbrb** [comment]
@manuelwedler has started working on this

**Comment by manuelwedler** [comment]
### Proposal 
@ulope showed me this [script](https://github.com/ulope/raiden-presence-monitor/blob/master/presence-monitor.py), which should make it pretty straight-forward to implement this. 

The explorer backend should generate a private key and use that to login into the Matrix server. It should join the discovery room and then add a listener on the presence in the room. That should be roughly the same as the function `monitor_server_presence` in the script.

The presence of the nodes should be stored in a dict, which should get updated by the callback of the listener. The dict can then be used on API calls. For building the network graph we already have an object in the API response, which maps the address of the nodes to their number of channels. The data from the dict should be appended to that structure. E.g.:
```
...
"nodes": {
   "0x6652f05286b003576d1dC3868C34F63AB65eF233": {
     "online": true,
     "opened": 2, 
     "closed": 0, 
     "settled": 1
   }
}
...
```

On the frontend we can then use this data in the network graph to mark online nodes green and offline ones red. Some text (online/offline) could also be shown in the tooltip on hover.

@ulope any remarks? / does that look good?

**Comment by palango** [comment]
We might also want to think about extending the PFS to provide the data required.

My thinking is that the explorer backend is kind of an old version of the PFS, and most of the stuff we implement now is already implemented in the PFS. Adding the required API endpoint would allow us to get rid of the extra codebase for the explorer backend.
