### ISSUE TITLE
Lookup nodes & channels

### ISSUE THREAD

**Issue by palango** [raiden-network/explorer#94]
> Would also make sense to look up channels for a specific address (i.e. I just opened a channel and want to see if it's there)

@kelsos As we talked it might make sense to add a search box for nodes and channel ids.

**Comment by kelsos** [comment]
@palango from a user perspective channel id would not make much sense would it? You would have to know the id to search with it.

I am thinking of some autocomplete input like the one in the token network filter. That searches nodes by the address and channels by the participant1/participant2. The suggestions have a label to distinct between channel/node and when you click on the suggested option it goes and selects it.

I am not sure if there will be any issues with this approach but this is what I would like to try and implement. What do you think of it?

**Comment by palango** [comment]
> from a user perspective channel id would not make much sense would it? You would have to know the id to search with it.

You could have gotten it from the REST API or the webUI and want to find it in the network!?

But I agree the nodes itself are more important.
